server:
    port: 8080
spring:
  profiles:
    active:
    - dev
---
spring:
    config:
      activate:
        on-profile: dev
    application:
        name: restfull-api
    jackson:
        default-property-inclusion: NON_NULL
        property-naming-strategy: SNAKE_CASE
    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_HOST}
        username: ${DB_USER}
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format-sql: true
        show-sql: true
---
spring:
    config:
      activate:
        on-profile: qa
    application:
        name: restfull-api
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/restfull_api_qa
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format-sql: true
        show-sql: true
---
spring:
    config:
      activate:
        on-profile: prod
    application:
        name: restfull-api
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/restfull_api_prod
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format-sql: true
        show-sql: true